2025-06-12 20:39:26,583:INFO:Loading model from experiments\additive_1x2_uniform\model-2000.pt for testing
2025-06-12 20:39:26,583:INFO:Model configuration:
 - Distribution: uniform
 - Num agents: 1
 - Num items: 2
2025-06-12 20:39:26,590:ERROR:Error testing model: [Errno 2] No such file or directory: 'experiments\\additive_1x2_uniform\\model-2000.pt'
2025-06-12 20:39:26,593:ERROR:Traceback (most recent call last):
  File "C:\Users\Artyom\kal\pytorch_regretNet\trainer\trainer.py", line 727, in test
    checkpoint = torch.load(model_path, map_location=self.device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artyom\kal\regretnet_env\Lib\site-packages\torch\serialization.py", line 1479, in load
    with _open_file_like(f, "rb") as opened_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artyom\kal\regretnet_env\Lib\site-packages\torch\serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Artyom\kal\regretnet_env\Lib\site-packages\torch\serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                     ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'experiments\\additive_1x2_uniform\\model-2000.pt'

